from typing import Any

from Xlib.protocol import event as event

# A union of the event fields the tray reads; python-xlib delivers a different
# concrete event class per type, but they share these attributes.
class Event:
    type: int
    window: Any
    detail: int
    client_type: int
    data: Any

# Resource objects (windows, GCs, pixmaps) and screens are returned as Any:
# python-xlib builds them dynamically and the tray code treats them loosely.
class Display:
    def __init__(self, display: str | None = ...) -> None: ...
    def screen(self, sno: int | None = ...) -> Any: ...
    def intern_atom(self, name: str, only_if_exists: bool = ...) -> int: ...
    def get_default_screen(self) -> int: ...
    def get_selection_owner(self, selection: int) -> Any: ...
    def create_resource_object(self, rtype: str, rid: int) -> Any: ...
    def grab_server(self) -> None: ...
    def ungrab_server(self) -> None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    def next_event(self) -> Event: ...
    def send_event(
        self,
        destination: Any,
        event: Any,
        event_mask: int = ...,
        propagate: bool = ...,
        onerror: Any = ...,
    ) -> None: ...
